name = "RemoteDesk"
description = "RemoteDesk"
version = "2.0.5-beta"
author = "Gabriel Aragão"

[app]
script = "main.py"

[product]
name = "RemoteDesk"
company = "Gabriel Aragão"
copyright = "Copyright (c) 2024 Gabriel Aragão"